plugins { id 'com.android.application' }
android { namespace 'za.co.deutronomagroup.droplink'; compileSdk 36
 defaultConfig { applicationId 'za.co.deutronomagroup.droplink'; minSdk 24; targetSdk 36; versionCode 1; versionName '1.0.0' }
 buildTypes { release { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } } }
